### ISSUE TITLE
关于预测结果的问题

### ISSUE THREAD

**Issue by zhaohuahauahua** [doratree/weighted_moving_forecasting_method#1]
请问一下如果预测值和实际值二者趋势相差较大，需要修改哪些参数？（下面是我的数据 以及结果图）
![2](https://github.com/ishelo/Logistics-Demand-Forecasting-By-Python/assets/168067597/a8842d1c-9516-44b1-9e21-107b428d68be)
![3](https://github.com/ishelo/Logistics-Demand-Forecasting-By-Python/assets/168067597/d333ac26-7cec-478b-ad4e-d93c633c2c8b)

**Comment by ishelo** [comment]
作者工作多年，已经忘记相应的知识(工作中并无相关)，建议你先做一个灰色关联度分析，去除一些不相关的变量。另外，从公路实际货量上看，有一个高峰后急剧下滑，应该是有一些关键因素影响（比如政策，需要你自己去深究一下）。另外这个建议使用滑动，预测结果可能会更好一点。
